### PR TITLE
Review request for user interface

### PR DESCRIPTION
**Pull request by chrystalme**
# Tic-tac-toe project review for user interface

- Request user input and assign a symbol
- mock play the game

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required ♻🛑**

<hr>

Hello team, GREAT job you've done so far on this project. However, there are still some changes to make before moving on to the next!

- [ ] Your game should display the board (without displaying which spots are taken!)
- [ ] Your game should display a winner (mock the game to display a winner at the end without actually computing it)
- [ ] Your game should show which player is currently playing (each player's name in their turns)
- [ ] Your game should detect an invalid move i.e. when the player enters 22!
- [ ] The main point of this milestone is to make you think about the logic you're going to make in the next one, so in order to make the above changes, think of the game as a loop and while game_on = true the game goes on but in case a win or a draw (mockery for now) the game stops.
logic

<hr>

Please make sure to do the changes before submitting for a re-review.
Good luck and happy coding👨‍💻💻

**Review by GzimAsani — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED  :stop_sign: 
### HELLO  **TEAM**  very nice project and you did a great job implementing the project requirements and implementing changes asked in the last review:+1:  nice work :+1:, however there is one more change that I want you to make:

- [ ] The game does not have any comment on calling the game as draw, kindly fix this.

### **Please make the required changes and submit another review request when you are ready.**

<hr>
### if you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑

## Hello team 👋,

**Great job on this milestone 👏. However, there is a requirement missing.**

1). **You have described the scenario for when a game is drawn, but there is no indication of a message alert to inform a player when a game is drawn.**


## Happy coding 🥂.

**PS: You can reach me on slack (Rose Wanjohi).**

**Review by cristianCeamatu — APPROVED** [review]
## 🥇  APPROVED
Congratulations! I can already see that this will become an awesome game. Please also check my suggestions that you can implement in the next milestone to make your game  🚀 !

### Suggestions
1. [Optional] Add `sleep` and colors to your game, this will totally transform your game and make it feel like it is not a simple CLI game. Links: [colors (the second answer is without using any gem)](https://stackoverflow.com/questions/1489183/colorized-ruby-output-to-the-terminal), and for [using sleep](https://stackoverflow.com/questions/1329967/tell-ruby-program-to-wait-some-amount-of-time).

Good luck with future projects and congratulations on this project!  
# 👍 🥇 👨‍💻 

Best regards,
Cristian Ceamatu
Slack: (Search `Cristian Viorel Ceamatu`)

**Pull request merged**
